### ISSUE TITLE
Possible to have XPANDR manipulation modules?

### ISSUE THREAD

**Issue by Chaircrusher** [Skrylar/skylights-vcv#5]
I noticed that connecting (for example) a random voltage source to an XPANDR jack doesn't do anything.  It would be cool to be able to mess with the XPANDR stream, but I don't think that any normal signal manipulation process produces a parse-able XPANDR signal.

In particular I would like to process the XPANDR signal to inject variation so that multiple Pulse and Voltage expanders could have different but related output.

**Comment by Chaircrusher** [comment]
Very useful also: A XPANDR delay, which would simply delay an XPANDR module a given number of milleseconds or clock pulses.

**Comment by Skrylar** [comment]
`XPND` is somewhat strange and abusive of the way Rack works. The exact reason inputting random values doesn't do anything is well documented in the manual, but the short version is that most signals in Rack are in the range [-5, 5] volts or [0, 10] volts and `XPND` is in the range of [0, 65535] volts. It uses this extra "head room" to ensure individual bits are not lost to imprecision dealing with floating points. This part can't be changed without breaking everyone's patches.

What _could_ be done is a _scaler_ that converts the `XPND` in to a normal signal and back again. This would let you use arbitrary modules on the turing machine's bitstream, although there is no guarantee that some bits would be changed due to losses (this may not actually matter to everyone.)

---

It may be worth running `XPND` through some normal mono delay lines. I don't think most modules clip their input/outputs and so this might actually work out of the box.

**Comment by Skrylar** [comment]
#11 #12
